### ISSUE TITLE
bug: token-wrapper-eth: doesn't compile out of the box

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/eth-tech-tree-challenges-old#54]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

After setting up the `token-wrapper-eth` + (install/foundry up), running `yarn foundry:test` (or `yarn compile`) returns:

![image](https://github.com/user-attachments/assets/34c2d08c-bc6e-4670-b224-7af4b1c0b352)

Just in case, I completed the challenge (filling in the missing stuff on the Contract), but still getting the same. If I remove the test with the warning + the tests with the events, it works.

![image](https://github.com/user-attachments/assets/2f2f1e63-028a-4c2a-8e92-061a241399ba)

### Expected Behavior

It should compile out of the box (maybe something is wrong with my foundry?)

### Steps To Reproduce

- yarn install
- foundryup
- yarn foundry:test

**Comment by escottalexander** [comment]
Thanks for raising this issue. I can't seem to replicate the problem. I just did a fresh clone and followed your exact steps and it compiles and returns all the tests failing.
![image](https://github.com/user-attachments/assets/12614de6-b9b4-466e-9094-da5dc0fb82f4)

I am on Linux as I believe you are. What other factors could be at play here?

Your `WrappedETH.sol` does contain the Deposit event, correct?

My Forge version:
```bash
[elliott@fedora temp_challenges]$ forge --version
forge 0.2.0 (0ad127a 2024-07-25T00:17:47.070402649Z)
```

**Comment by damianmarti** [comment]
@escottalexander I'm having the same behavior on the eth-streaming branch. 

When I tried to deploy the contracts I'm getting:

yarn deploy
[⠊] Compiling...
[⠰] Compiling 1 files with Solc 0.8.19
[⠔] Solc 0.8.19 finished in 275.74ms
Error: 
Compiler run failed:
Error (9582): Member "EthReceived" not found or not visible after argument-dependent lookup in type(contract EthStreaming).
  --> test/EthStreaming.t.sol:48:14:
   |
48 |         emit EthStreaming.EthReceived(sender, amount); // test contract
   |              ^^^^^^^^^^^^^^^^^^^^^^^^

Ubuntu with forge 0.2.0 (0ad127a 2024-07-25T00:17:47.070402649Z)

**Comment by escottalexander** [comment]
@carletex What Solc version does it use when you run `yarn compile`? This is different between Damu and I:
```bash
[elliott@fedora temp_challenges]$ yarn compile
[⠊] Compiling...
[⠑] Compiling 2 files with Solc 0.8.22
[⠘] Solc 0.8.22 finished in 572.32ms
Compiler run successful!
```

**Comment by escottalexander** [comment]
When I specify `solc_version='0.8.19` in `foundry.toml` I get the same errors you both get. I think the solution will be specifying `solc_version='0.8.22'` but I will need to look into it more to make sure this is not short sighted. Please confirm that adding `solc_version='0.8.22'` fixes your issues when you get a chance. Thanks!

**Comment by damianmarti** [comment]
> @carletex What Solc version does it use when you run `yarn compile`? This is different between Damu and I:
> 
> ```shell
> [elliott@fedora temp_challenges]$ yarn compile
> [⠊] Compiling...
> [⠑] Compiling 2 files with Solc 0.8.22
> [⠘] Solc 0.8.22 finished in 572.32ms
> Compiler run successful!
> ```

This is because the contract is set:

pragma solidity >=0.8.0 <0.9.0;

I always try to use something like 

pragma solidity 0.8.22;

To set the solidity version to the chosen one.

**Comment by damianmarti** [comment]
> When I specify `solc_version='0.8.19` in `foundry.toml` I get the same errors you both get. I think the solution will be specifying `solc_version='0.8.22'` but I will need to look into it more to make sure this is not short sighted. Please confirm that adding `solc_version='0.8.22'` fixes your issues when you get a chance. Thanks!

Yes! It worked!

**Comment by carletex** [comment]
I had `0.8.20` and it was failing. `0.8.22`avoids the error with events (still showing the `Return value of low-level calls not used.`warning tho). But test results show correctly now.

I think locking the version could be a safe approach.Or at least ^0.8.22

Thanks for the quick response!                                                                                                                                                                                              │

**Comment by escottalexander** [comment]
This has been solved in each of the challenge branches and the main branch.
